name: midap
channels:
  - defaults
dependencies:
  - pip
  - pip:
    - btrack>=0.4.6
    - coverage>=7.3.2
    - gitpython>=3.1.40
    - napari>=0.4.18
    - omnipose==0.4.4
    - opencv-python>=4.8.1
    - pandas>=2.0.2
    - scikit-image>=0.19.3,<=0.20.0
    - stardist==0.8.5
    - tensorflow==2.15.0
    - tqdm>=4.65.0
    - -e .
